help([[
Load environment to run EMC_verif-global on Hera using Intel
]])

prepend_path("MODULEPATH", '/scratch1/NCEPDEV/global/David.Huber/SPACK/ss_1.8.0/envs/gsi-addon/install/modulefiles/Core')


stack_intel_ver=os.getenv("stack_intel_ver","2021.5.0")
load(pathJoin("stack-intel",stack_intel_ver))
stack_intel_oneapi_mpi_ver=os.getenv("stack_intel_oneapi_mpi_ver","2021.5.1")
load(pathJoin("stack-intel-oneapi-mpi",stack_intel_oneapi_mpi_ver))
stack_python_ver=os.getenv("stack_python_ver","3.11.7")
load(pathJoin("stack-python",stack_python_ver))
netcdf_c_ver=os.getenv("netcdf_c_ver","4.9.2")
load(pathJoin("netcdf-c",netcdf_c_ver))
netcdf_fortran_ver=os.getenv("netcdf_fortran_ver","4.6.1")
load(pathJoin("netcdf-fortran",netcdf_fortran_ver))
py_netcdf4_ver=os.getenv("py_netcdf4_ver","1.5.8")
load(pathJoin("py-netcdf4",py_netcdf4_ver))
py_numpy_ver=os.getenv("py_numpy_ver","1.23.5")
load(pathJoin("py-numpy",py_numpy_ver))
py_pandas_ver=os.getenv("py_pandas_ver","1.5.3")
load(pathJoin("py-pandas",py_pandas_ver))
py_matplotlib_ver=os.getenv("py_matplotlib_ver","3.7.4")
load(pathJoin("py-matplotlib",py_matplotlib_ver))
py_cartopy_ver=os.getenv("py_cartopy_ver","0.23.0")
load(pathJoin("py-cartopy",py_cartopy_ver))
wgrib2_ver=os.getenv("wgrib2_ver","3.1.1")
load(pathJoin("wgrib2",wgrib2_ver))
met_ver=os.getenv("met_ver","9.1.3")
load(pathJoin("met",met_ver))
metplus_ver=os.getenv("metplus_ver","3.1.1")
load(pathJoin("metplus",metplus_ver))
prod_util_ver=os.getenv("prod_util_ver","2.1.1")
load(pathJoin("prod_util",prod_util_ver))
grib_util_ver=os.getenv("grib_util_ver","1.4.0")
load(pathJoin("grib-util",grib_util_ver))
grads_ver=os.getenv("grads_ver","2.2.3")
load(pathJoin("grads",grads_ver))
